name: prelude
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://github.com/dnunez24/prelude

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  effective_dart: ^1.0.0
  pedantic: ^1.9.0
  test: ^1.14.4
